### ISSUE TITLE
NullReferenceException at GoogleSignIn_Result

### ISSUE THREAD

**Issue by kaworucloud** [Thaina/google-signin-unity#46]
I'm testing this feature on Android device.
I wrote this simple code from the sample, and the native login dialog displayed successfully.
But when I select a account to sign in, I got a null reference exception.
What did I do wrong?

Environment
Unity 6000.0.54f1, 6000.1.14f1
Android 13

```
void Start()
{
    m_Configuration = new GoogleSignInConfiguration
    {
        WebClientId = m_strWebClientId,
        RequestIdToken = true
    };
}

public void OnGoogleSignIn()
{
    GoogleSignIn.Configuration = m_Configuration;
    GoogleSignIn.Configuration.UseGameSignIn = false;
    GoogleSignIn.DefaultInstance.SignIn().ContinueWith(OnAuthenticationFinished, TaskScheduler.FromCurrentSynchronizationContext());
}

internal void OnAuthenticationFinished(Task<GoogleSignInUser> task)
{
    // breakpoint not triggered
}
```

Error stack from Logcat:
NullReferenceException: Object reference not set to an instance of an object.
   at Google.Impl.GoogleSignInImpl.GoogleSignIn_Result (System.Runtime.InteropServices.HandleRef self) [0x00005] in .\Library\PackageCache\com.google.signin@ce996c127c02\GoogleSignIn\Impl\GoogleSignInImpl.cs:187 
   at Google.Impl.NativeFuture.get_Result () [0x00009] in .\Library\PackageCache\com.google.signin@ce996c127c02\GoogleSignIn\Impl\NativeFuture.cs:38 
   at Google.Future`1[T].get_Result () [0x00007] in .\Library\PackageCache\com.google.signin@ce996c127c02\GoogleSignIn\Future.cs:65 
   at Google.Future`1+<WaitForResult>d__8[T].MoveNext () [0x000c0] in .\Library\PackageCache\com.google.signin@ce996c127c02\GoogleSignIn\Future.cs:79 
   at UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) [0x00027] in \home\bokken\build\output\unity\unity\Runtime\Export\Scripting\Coroutines.cs:17

**Comment by Thaina** [comment]
The actual problem seem to be other previous error stack. If there is no log with `credential.getType` it more likely the initialization is not properly called

**Comment by kaworucloud** [comment]
I found there is a NoClassDefFoundError occurred earlier.
But both Release and Debug Minify settings are unchecked and Android Resolver resolved successfully.
I have no idea what's causing this error.

AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;
  at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
  at java.lang.reflect.Method.getParameterTypes(Method.java:186)
  at java.lang.Class.getDeclaredMethods(Class.java:2741)
  ...

**Comment by Thaina** [comment]
@kaworucloud That kind of error seem likely about minify and proguard. Can you first disable any option related to minify and pruning in your project and see if you can build and make it work?

**Comment by kaworucloud** [comment]
Both Release and Debug Minify settings are unchecked, except this how could I disable the minify function?

**Comment by Thaina** [comment]
Then, do you install EDM4U and resolve dependency?

**Comment by standegg-heeju** [comment]
Hello, I'm facing this issue ! I have two cases.
Unity 2022.3.62f1 , build with AGP 8.1.4 (I use gradle version 8.1.1) with JDK 17
Android 14 -> works fine.
but on Android 12 I have this error below.
`NullReferenceException Google.Impl.GoogleSignInImpl.GoogleSignIn_Result (System.Runtime.InteropServices.HandleRef self) (at <00000000000000000000000000000000>:0) Google.Impl.NativeFuture.get_Result () (at <00000000000000000000000000000000>:0) Google.Future`1+<WaitForResult>d__8[T].MoveNext () (at <00000000000000000000000000000000>:0) UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <00000000000000000000000000000000>:0)`

these result from same aab file..
I removed EDM4U from asset folder and get new one from git url. Could..this be a problem ?
and I did force resolve before build
I don't enabled minify and currently not using proguard

**Comment by anhnguyenSb** [comment]
Anyone solved this problem, i have same problem on Android 12

**Comment by Thaina** [comment]
@standegg-heeju If it can work in android 14 with the same aab then it would not related to EDM4U or your code. But the compatible of android SDK version itself. I am sorry but this need thorough investigation in dependency configuration

I suspect that your aab might only contain apk that compatible with android 14. Or maybe not about android version but the build target (arm/x86/x64) that compatible with only one of your device. (aab is actually just a zip that contains multiple apk files and shared asset)

@kaworucloud Could you please try your build on other device? Especially android 14

**Comment by Thaina** [comment]
Also please anyone could make some very basic repo that got this problem for me to check the configuration?

**Comment by anhnguyenSb** [comment]
Hello @Thaina , this is my config, it not work on my device with Android 12 but work in my other device on Android 14, when i include     "com.google.signin": "https://github.com/Thaina/google-signin-unity.git#master" -> it worked both. I think Android 12 can not work with Credential
<img width="1444" height="615" alt="Image" src="https://github.com/user-attachments/assets/33e5fcce-7898-43eb-b2c5-a669400f48b8" />

**Comment by anhnguyenSb** [comment]
implementation 'androidx.credentials:credentials:1.2.0-alpha02'
implementation 'androidx.credentials:credentials-play-services-auth:1.2.0-alpha02' -> not work in Android 12, i think so @Thaina

**Comment by Thaina** [comment]
@anhnguyenSb That might be possible. I start to suspect that `Credential` class was really not exist in older android OS

The master branch was the old code from google itself so it would work fine in older device

**Comment by anhnguyenSb** [comment]
Yes, my current solution to solved this is use master with Android Build and use newmigration with iOS Build. Hope you will fix it soon, thank you very much @Thaina

**Comment by Thaina** [comment]
@anhnguyenSb Could you please try fork this repo and change dependencies here

https://github.com/Thaina/google-signin-unity/blob/ce996c127c02d60e824514a04e4f3d05b734b706/GoogleSignIn/Editor/GoogleSignInDependencies.xml#L5-L9

to `1.6.0-alpha04` ?

Cause in here https://developer.android.com/jetpack/androidx/releases/credentials#version_16_2

> The Credential Manager dialogs will now look more consistent across Android versions before and after Android 14, on mobile and wearable devices

This should imply it work in every version?

Actually in my understanding it should work since `1.5.0`. Why your gradle are still `1.2.0-alpha02` ?

Have you update this package to the latest commit?

**Comment by anhnguyenSb** [comment]
okay let me try @Thaina

**Comment by anhnguyenSb** [comment]
@Thaina my gradle is 1.5.0, that's just an example i send you :D

**Comment by anhnguyenSb** [comment]
Both   <androidPackage spec="androidx.credentials:credentials:1.5.0" /> 
   <androidPackage spec="androidx.credentials:credentials-play-services-auth:1.5.0" />  to 1.6.0-alpha04, right? @Thaina

**Comment by Thaina** [comment]
I think so, it should come in pair?

**Comment by Thaina** [comment]
One thing I am not sure is minSDKVersion setting. If we up it to 34 or more, could it still installed in android 12 device?

**Comment by anhnguyenSb** [comment]
@Thaina hmm i'm not sure but seem right. but my game need to public to Google Play Store and this is my config 

<img width="1077" height="68" alt="Image" src="https://github.com/user-attachments/assets/f0f0bf51-d25b-455e-81c7-51f1f89f6371" />

**Comment by standegg-heeju** [comment]
> [@standegg-heeju](https://github.com/standegg-heeju) If it can work in android 14 with the same aab then it would not related to EDM4U or your code. But the compatible of android SDK version itself. I am sorry but this need thorough investigation in dependency configuration
> 
> I suspect that your aab might only contain apk that compatible with android 14. Or maybe not about android version but the build target (arm/x86/x64) that compatible with only one of your device. (aab is actually just a zip that contains multiple apk files and shared asset)
> 
> [@kaworucloud](https://github.com/kaworucloud) Could you please try your build on other device? Especially android 14

<img width="605" height="60" alt="Image" src="https://github.com/user-attachments/assets/70a460ea-0e61-4a86-be67-bce8c92fd769" />
this is my current api level setting

<img width="353" height="173" alt="Image" src="https://github.com/user-attachments/assets/0ac6e8ee-8287-448c-8f6a-77ef1d60a79d" />
and this is my architecture setting.

I've tested with 4 different devices.

**Comment by standegg-heeju** [comment]
> One thing I am not sure is minSDKVersion setting. If we up it to 34 or more, could it still installed in android 12 device?

installation was just fine.
I've installed my app through Play Store.

**Comment by Thaina** [comment]
As far as I can investigate right now. I suspect this issue couldn't be fixed easily. I need to track down which line of code that call `android.credentials.Credential` instead of `androidx.credentials.Credential`

First thing first, I think `NullReferenceException at GoogleSignIn_Result` is the misleading error. The cause itself is the credential system was not initialize properly so the task object was still `null`. The cause of error more likely thrown from Java somewhere before this line

Can @standegg-heeju @anhnguyenSb help me confirm that you both has the same error as @kaworucloud in this https://github.com/Thaina/google-signin-unity/issues/46#issuecomment-3154110592 comment? So I can make sure that the issue is exactly the same, or are there any more problem about initialization

**Comment by standegg-heeju** [comment]
@Thaina  Yes, after I saw that thread, I check it too and there was exactly same error log.
error below.. !

`2025-08-06 19:08:58.414 21151 21151 Error Unity AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;
2025-08-06 19:08:58.414 21151 21151 Error Unity java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at java.lang.reflect.Executable.getParameterTypesInternal(Native Method)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at java.lang.reflect.Method.getParameterTypes(Method.java:186)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at java.lang.Class.getDeclaredMethods(Class.java:1915)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.unity3d.player.ReflectionHelper.getMethodID(Unknown Source:26)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.unity3d.player.ReflectionHelper.nativeProxyInvoke(Native Method)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.unity3d.player.ReflectionHelper.-$$Nest$smnativeProxyInvoke(Unknown Source:0)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.unity3d.player.L.invoke(Unknown Source:22)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at $Proxy26.onAuthenticated(Unknown Source)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.google.googlesignin.GoogleSignInHelper$1$4.then(GoogleSignInHelper.java:199)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.google.googlesignin.GoogleSignInHelper$1$4.then(GoogleSignInHelper.java:190)
2025-08-06 19:08:58.414 21151 21151 Error Unity 	at com.google.android.gms.tasks.zzo.run(com.google.android.gms:play-services-tasks@@`

**Comment by Thaina** [comment]
Let's see

Could you try forking this and changing these lines

https://github.com/Thaina/google-signin-unity/blob/ce996c127c02d60e824514a04e4f3d05b734b706/GoogleSignIn/Impl/GoogleSignInImpl.cs#L130-L155

Could you removing line that just call `?.Dispose()` and see if it will still throw error?

**Comment by anhnguyenSb** [comment]
@Thaina i trying with version 1.6.0-alpha04, but still error in Android 12 Device, still have problem with AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;

**Comment by standegg-heeju** [comment]
@Thaina It doesn't work. Still have same errors before.

`	public class SignInListener : AndroidJavaProxy
	{
		public SignInListener() : base("com.google.googlesignin.IListener") { }

	    public void onAuthenticated(AndroidJavaObject _googleIdTokenCredential)
		{
			// googleIdTokenCredential?.Dispose();
			googleIdTokenCredential = _googleIdTokenCredential;
		}

    	public void onAuthorized(AndroidJavaObject _authorizationResult)
		{
			// authorizationResult?.Dispose();
			authorizationResult = _authorizationResult;
		}

		public void onFailure(AndroidJavaObject exception)
		{
			Debug.LogErrorFormat("onFailure {0} : {1}",exception?.Call<AndroidJavaObject>("getClass").Call<string>("toString"),exception?.Call<string>("getMessage"));
			exception.Dispose();
		}

		public void onCanceled() {
			// googleIdTokenCredential?.Dispose();
			// authorizationResult?.Dispose();
		}
	}`

**Comment by Thaina** [comment]
I would like to ask what is the android target SDK in each of your project setting?

Could you please try to set it to 35 or more in unity?

**Comment by standegg-heeju** [comment]
> I would like to ask what is the android target SDK in each of your project setting?
> 
> Could you please try to set it to 35 or more in unity?

Mine is target 35, min 24

**Comment by Thaina** [comment]
How many plugin you are using?

Can you show me gradle in your project after resolve dependency?

**Comment by standegg-heeju** [comment]
@Thaina This is my mainTemplate file.

apply plugin: 'com.android.library'
**APPLY_PLUGINS**

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
// Android Resolver Dependencies Start
    implementation 'androidx.recyclerview:recyclerview:1.2.1' // Assets/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:9
    implementation 'com.android.support:appcompat-v7:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:cardview-v7:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    // implementation 'com.android.support:customtabs:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.android.support:customtabs:28.+' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:7
    implementation 'com.android.support:recyclerview-v7:28.+' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:6
    implementation 'com.android.support:support-v4:25.3.1' // Facebook.Unity.Editor.AndroidSupportLibraryResolver.addSupportLibraryDependency
    implementation 'com.applovin.mediation:bytedance-adapter:6.3.0.4.0' // Assets/MaxSdk/Mediation/ByteDance/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:facebook-adapter:[6.18.0.1]' // Assets/MaxSdk/Mediation/Facebook/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:fyber-adapter:8.3.5.0' // Assets/MaxSdk/Mediation/Fyber/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:google-adapter:[23.5.0.0]' // Assets/MaxSdk/Mediation/Google/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:google-ad-manager-adapter:[23.5.0.0]' // Assets/MaxSdk/Mediation/GoogleAdManager/Editor/Dependencies.xml:5
    implementation 'com.applovin.mediation:inmobi-adapter:10.7.8.1' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:ironsource-adapter:8.4.0.0.1' // Assets/MaxSdk/Mediation/IronSource/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:line-adapter:2024.8.27.1' // Assets/MaxSdk/Mediation/Line/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:mintegral-adapter:16.8.71.0' // Assets/MaxSdk/Mediation/Mintegral/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:moloco-adapter:3.3.0.1' // Assets/MaxSdk/Mediation/Moloco/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:pubmatic-adapter:4.1.0.0' // Assets/MaxSdk/Mediation/PubMatic/Editor/Dependencies.xml:8
    implementation 'com.applovin.mediation:unityads-adapter:4.12.4.0' // Assets/MaxSdk/Mediation/UnityAds/Editor/Dependencies.xml:4
    implementation 'com.applovin.mediation:vungle-adapter:7.4.1.4' // Assets/MaxSdk/Mediation/Vungle/Editor/Dependencies.xml:4
    implementation 'com.applovin:applovin-sdk:13.3.1' // Assets/MaxSdk/AppLovin/Editor/Dependencies.xml:4
    implementation 'com.facebook.android:facebook-applinks:[17.0.1]' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:6
    implementation 'com.facebook.android:facebook-core:[17.0.1]' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:5
    implementation 'com.facebook.android:facebook-gamingservices:[17.0.1]' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:9
    implementation 'com.facebook.android:facebook-login:[17.0.1]' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:7
    implementation 'com.facebook.android:facebook-share:[17.0.1]' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:8
    implementation 'com.google.android.gms:play-services-auth:20+' // Assets/GoogleSignIn/Editor/GoogleSignInDependencies.xml:10
    implementation 'com.google.android.gms:play-services-base:18.4.0' // Assets/Firebase/Editor/AppDependencies.xml:17
    implementation 'com.google.android.play:core-common:2.0.4' // Assets/GooglePlayPlugins/com.google.play.core/Editor/Dependencies.xml:3
    implementation 'com.google.android.play:review:2.0.0' // Assets/GooglePlayPlugins/com.google.play.review/Editor/Dependencies.xml:3
    implementation 'com.google.android.ump:user-messaging-platform:2.1.0' // Assets/MaxSdk/AppLovin/Editor/Dependencies.xml:5
    implementation 'com.google.firebase:firebase-analytics:21.6.2' // Assets/Firebase/Editor/MessagingDependencies.xml:15
    implementation 'com.google.firebase:firebase-analytics-unity:11.9.0' // Assets/Firebase/Editor/AnalyticsDependencies.xml:18
    implementation 'com.google.firebase:firebase-app-unity:11.9.0' // Assets/Firebase/Editor/AppDependencies.xml:22
    implementation 'com.google.firebase:firebase-auth:22.3.1' // Assets/Firebase/Editor/AuthDependencies.xml:13
    implementation 'com.google.firebase:firebase-auth-unity:11.9.0' // Assets/Firebase/Editor/AuthDependencies.xml:20
    implementation 'com.google.firebase:firebase-common:20.4.3' // Assets/Firebase/Editor/AppDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-ndk:18.6.4' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:13
    implementation 'com.google.firebase:firebase-crashlytics-unity:11.9.0' // Assets/Firebase/Editor/CrashlyticsDependencies.xml:20
    implementation 'com.google.firebase:firebase-iid:21.1.0' // Assets/Firebase/Editor/MessagingDependencies.xml:17
    implementation 'com.google.firebase:firebase-messaging:23.4.1' // Assets/Firebase/Editor/MessagingDependencies.xml:13
    implementation 'com.google.firebase:firebase-messaging-unity:11.9.0' // Assets/Firebase/Editor/MessagingDependencies.xml:24
    implementation 'com.google.flatbuffers:flatbuffers-java:1.12.0' // Assets/Firebase/Editor/MessagingDependencies.xml:19
    implementation 'com.google.signin:google-signin-support:1.0.4' // Assets/GoogleSignIn/Editor/GoogleSignInSupportDependencies.xml:9
    implementation 'com.parse.bolts:bolts-android:1.4.0' // Assets/FacebookSDK/Plugins/Editor/Dependencies.xml:4
    implementation 'com.squareup.picasso:picasso:2.71828' // Assets/MaxSdk/Mediation/InMobi/Editor/Dependencies.xml:5
    implementation 'io.airbridge:sdk-android:4.5.0' // Assets/Airbridge/Plugins/Editor/Dependencies.xml:8
// Android Resolver Dependencies End
**DEPS**}

// Android Resolver Exclusions Start
android {
  packagingOptions {
      exclude ('/lib/armeabi/*' + '*')
      exclude ('/lib/mips/*' + '*')
      exclude ('/lib/mips64/*' + '*')
      exclude ('/lib/x86/*' + '*')
      exclude ('/lib/x86_64/*' + '*')
  }
}
// Android Resolver Exclusions End
android {
    namespace '**APPLICATIONID**'
    ndkPath "**NDKPATH**"

    compileSdkVersion **APIVERSION**
    buildToolsVersion '**BUILDTOOLS**'

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }

    defaultConfig {
        minSdkVersion **MINSDKVERSION**
        targetSdkVersion **TARGETSDKVERSION**
        ndk {
            abiFilters **ABIFILTERS**
        }
        versionCode **VERSIONCODE**
        versionName '**VERSIONNAME**'
        consumerProguardFiles 'proguard-unity.txt'**USER_PROGUARD**
    }

    lintOptions {
        abortOnError false
    }

    aaptOptions {
        noCompress = **BUILTIN_NOCOMPRESS** + unityStreamingAssets.tokenize(', ')
        ignoreAssetsPattern = "!.svn:!.git:!.ds_store:!*.scc:!CVS:!thumbs.db:!picasa.ini:!*~"
    }**PACKAGING_OPTIONS**

    buildFeatures {
        buildConfig false // BuildConfig 파일 생성을 끔
    }
}
**IL_CPP_BUILD_SETUP**
**SOURCE_BUILD_SETUP**
**EXTERNAL_SOURCES**

**Comment by Thaina** [comment]
I suspect this could be conflict dependencies

Is it possible if you please try create plain new empty project with only these

```json
   "com.google.external-dependency-manager": "https://github.com/googlesamples/unity-jar-resolver.git?path=upm",
    "com.google.signin": "https://github.com/Thaina/google-signin-unity.git#newmigration",
```

and some basic assets, but without other 3rd party asset like facebook and google play ?

**Comment by intellectual-Dev** [comment]
Facing same issue for Android 12 build: 

> NullReferenceException: Object reference not set to an instance of an object.
> at Google.Impl.GoogleSignInImpl.GoogleSignIn_Result
> 
> AndroidJavaException: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;
> java.lang.NoClassDefFoundError: Failed resolution of: Landroid/credentials/Credential;

Both Release and Debug Minify settings are unchecked.
using Unity 6, It works fine for Android 13 and above but getting above error message on Android 12 and below
Any solution for this error message is greatly appreciated.  
Thanks

**Comment by standegg-heeju** [comment]
> I suspect this could be conflict dependencies
> 
> Is it possible if you please try create plain new empty project with only these
> 
>    "com.google.external-dependency-manager": "https://github.com/googlesamples/unity-jar-resolver.git?path=upm",
>     "com.google.signin": "https://github.com/Thaina/google-signin-unity.git#newmigration",
> and some basic assets, but without other 3rd party asset like facebook and google play ?

firebase sdk and google sign in only ?

**Comment by Thaina** [comment]
Let's test without firebase first

**Comment by MohamedAshrafElSayed** [comment]
I have the same problem, so I wanted to know if you have found a solution ?

**Comment by Thaina** [comment]
@MohamedAshrafElSayed Have you try things on above comments?

**Comment by Thaina** [comment]
Some people have try forking and downgrade `androidx.credentials:credentials` to 1.3.0

https://github.com/Thaina/google-signin-unity/issues/51#issuecomment-3314604034

Anyone still have problem could you try this?

**Comment by MohamedAshrafElSayed** [comment]
After downgrading `androidx.credentials:credentials` to 1.3.0, as you said it worked for Android < 14 as well.

**Comment by Nyankoo** [comment]
I downgraded androidx.credentials:credentials to 1.3.0 but it still throws the exception on Android 10.

**Comment by Nyankoo** [comment]
@Thaina No updates on this issue?

**Comment by Thaina** [comment]
@Nyankoo Android 10 is too old I don't have anyway to test it

**Comment by poobool-koon** [comment]
@Thaina Some emulators(ex. Nox, Bluestack) supports old version Androids. (ex. 7, 9, 11) I think you can use them.

**Comment by Thaina** [comment]
I have test latest commit in bluestack with android 9 (pie) and it's work. Could anyone help verify it?
